name: Python CI

on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Run Static Analysis
      run: pylint shopping_cart.py
